2020-03-17 13:53:50,196 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 559740ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 14:59:02,703 ERROR 75062 [-/127.0.0.1/-/21ms POST /api/postDetailInfo] nodejs.TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at Register.registerDetailInfo (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/register.js:79:23)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:45:18)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:36:12

pid: 75062
hostname: zhendeMacBook-Pro.local

2020-03-17 15:04:32,128 ERROR 75162 [-/127.0.0.1/-/2ms POST /api/postDetailInfo] nodejs.TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at Register.registerDetailInfo (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/register.js:79:23)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:45:18)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:36:12

pid: 75162
hostname: zhendeMacBook-Pro.local

2020-03-17 15:08:03,234 ERROR 75225 [-/127.0.0.1/-/2ms POST /api/postDetailInfo] nodejs.TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at Register.registerDetailInfo (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/register.js:79:15)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:45:18)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:36:12

pid: 75225
hostname: zhendeMacBook-Pro.local

2020-03-17 15:14:45,033 ERROR 75364 [-/127.0.0.1/-/28ms POST /api/postDetailInfo] nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'man' for column 'sex' at row 1
    at Query.Sequence._packetToError (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Pool.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    sql: INSERT INTO `user`(`name`, `sex`, `email`, `tel`, `account_id`) VALUES('35', 'man', '22@qq.com', '11111111111', 5)
code: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"
errno: 1366
sqlMessage: "Incorrect integer value: 'man' for column 'sex' at row 1"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`name`, `sex`, `email`, `tel`, `account_id`) VALUES('35', 'man', '22@qq.com', '11111111111', 5)"
name: "ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError"
pid: 75364
hostname: zhendeMacBook-Pro.local

2020-03-17 15:31:00,219 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 568595ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 15:42:44,239 ERROR 75551 [-/127.0.0.1/-/5ms POST /api/postDetailInfo] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '0' for key 'user.sex_UNIQUE'
    at Query.Sequence._packetToError (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Pool.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    sql: INSERT INTO `user`(`name`, `sex`, `email`, `tel`, `account_id`, `code`, `agent`) VALUES('23', 0, '23@qq.com', '11222222222', 5, '222', 1)
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '0' for key 'user.sex_UNIQUE'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`name`, `sex`, `email`, `tel`, `account_id`, `code`, `agent`) VALUES('23', 0, '23@qq.com', '11222222222', 5, '222', 1)"
name: "ER_DUP_ENTRYError"
pid: 75551
hostname: zhendeMacBook-Pro.local

2020-03-17 16:06:37,714 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 722567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 18:14:28,303 ERROR 78733 [-/127.0.0.1/-/5ms GET /api/confirmAudit] nodejs.Error: Can not auto detect update condition, please set options.where, or make sure obj.id exists
    at RDSClient.proto.update (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:151:13)
    at proto.update.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as update] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:30:15)
    at RegisterService.modifyRegisterState (/Users/yao37/projects/practices/graduation-project/egg_system/app/service/register.js:32:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Register.confirmAudit (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/register.js:142:30)

pid: 78733
hostname: zhendeMacBook-Pro.local

2020-03-17 19:53:26,009 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 576750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 20:03:42,129 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 575925ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 20:13:58,228 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 575844ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 20:29:47,348 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 908789ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 20:39:43,426 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 575676ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 20:48:49,548 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 505630ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 21:47:25,265 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 156581ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 21:54:50,440 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 124983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

2020-03-17 22:57:38,983 ERROR 82146 [-/127.0.0.1/-/174ms POST /api/uploadFile] nodejs.ReferenceError: ownFile is not defined
    at Order.uploadFile (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:13:30)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at next (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:45:18)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:44:32)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-compose/index.js:36:12

pid: 82146
hostname: zhendeMacBook-Pro.local

2020-03-17 23:42:12,302 ERROR 58754 nodejs.ClusterClientNoResponseError: client no response in 2318221ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 58754
hostname: zhendeMacBook-Pro.local

