2020-03-20 01:20:01,087 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 1836825ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 18:50:14,223 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 575395ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 19:00:10,297 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 576047ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 19:10:26,286 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 575978ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 19:20:23,384 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 577077ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 19:36:14,936 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 314267ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 19:44:07,489 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 372519ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 20:49:28,954 ERROR 14366 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'account_id' in 'where clause'
    at Query.Sequence._packetToError (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Pool.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    sql: SELECT * FROM `account` WHERE `account_id` = 5 LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'account_id' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `account` WHERE `account_id` = 5 LIMIT 0, 1"
name: "unhandledRejectionError"
pid: 14366
hostname: zhendeMacBook-Pro.local

2020-03-20 21:16:37,926 ERROR 14772 [-/127.0.0.1/-/24ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:136:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 14772
hostname: zhendeMacBook-Pro.local

2020-03-20 21:22:52,732 ERROR 14850 [-/127.0.0.1/-/17ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:137:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 14850
hostname: zhendeMacBook-Pro.local

2020-03-20 21:23:15,208 ERROR 14885 [-/127.0.0.1/-/14ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:136:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 14885
hostname: zhendeMacBook-Pro.local

2020-03-20 21:23:25,375 ERROR 14900 [-/127.0.0.1/-/15ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:136:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 14900
hostname: zhendeMacBook-Pro.local

2020-03-20 21:24:38,299 ERROR 14926 [-/127.0.0.1/-/16ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:137:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 14926
hostname: zhendeMacBook-Pro.local

2020-03-20 21:25:28,712 ERROR 14926 [-/127.0.0.1/-/5ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:137:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)

pid: 14926
hostname: zhendeMacBook-Pro.local

2020-03-20 21:26:05,561 ERROR 14969 [-/127.0.0.1/-/14ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.ReferenceError: orderList is not defined
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:129:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-static-cache/index.js:53:56

pid: 14969
hostname: zhendeMacBook-Pro.local

2020-03-20 21:49:17,479 ERROR 15380 [-/127.0.0.1/-/130ms POST /api/addOrder] nodejs.TypeError: ctx.service.order.addOrder is not a function
    at Order.addOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:94:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 15380
hostname: zhendeMacBook-Pro.local

2020-03-20 21:50:30,395 ERROR 15454 [-/127.0.0.1/-/106ms POST /api/addOrder] nodejs.ER_DUP_ENTRYError: ER_DUP_ENTRY: Duplicate entry '6' for key 'order.userid_UNIQUE'
    at Query.Sequence._packetToError (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Pool.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    sql: INSERT INTO `order`(`userid`, `patient_name`, `patient_height`, `patient_weight`, `patient_sex`, `patient_part`, `patient_org`, `data_id`, `access_id`, `order_number`) VALUES(6, '2322', '23', '23', '0', '喉咙', '关节', 7, 7, '2020021202150303D00000')
code: "ER_DUP_ENTRY"
errno: 1062
sqlMessage: "Duplicate entry '6' for key 'order.userid_UNIQUE'"
sqlState: "23000"
index: 0
sql: "INSERT INTO `order`(`userid`, `patient_name`, `patient_height`, `patient_weight`, `patient_sex`, `patient_part`, `patient_org`, `data_id`, `access_id`, `order_number`) VALUES(6, '2322', '23', '23', '0', '喉咙', '关节', 7, 7, '2020021202150303D00000')"
name: "ER_DUP_ENTRYError"
pid: 15454
hostname: zhendeMacBook-Pro.local

2020-03-20 21:52:55,442 ERROR 15589 [-/127.0.0.1/-/13ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:138:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 15589
hostname: zhendeMacBook-Pro.local

2020-03-20 21:53:52,496 ERROR 15624 [-/127.0.0.1/-/14ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:138:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 15624
hostname: zhendeMacBook-Pro.local

2020-03-20 21:54:12,494 ERROR 15642 [-/127.0.0.1/-/14ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.TypeError: orderResult.slice is not a function
    at Order.rangeOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:138:27)
    at Order.getUserOrder (/Users/yao37/projects/practices/graduation-project/egg_system/app/controller/order.js:126:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/koa-bodyparser/index.js:86:5)

pid: 15642
hostname: zhendeMacBook-Pro.local

2020-03-20 21:56:10,895 ERROR 15699 [-/127.0.0.1/-/94ms GET /api/getUserOrder?userAccount=&page=1&perPage=10] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'created_at' in 'order clause'
    at Query.Sequence._packetToError (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Pool.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:65:19)
    at /Users/yao37/projects/practices/graduation-project/egg_system/node_modules/co/index.js:54:5
    sql: SELECT * FROM `order` WHERE `userid` = 6 ORDER BY `created_at` DESC, `id` DESC LIMIT 0, 10
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'created_at' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `order` WHERE `userid` = 6 ORDER BY `created_at` DESC, `id` DESC LIMIT 0, 10"
name: "ER_BAD_FIELD_ERRORError"
pid: 15699
hostname: zhendeMacBook-Pro.local

2020-03-20 23:41:14,673 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 571211ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-20 23:51:31,379 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 576684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-21 00:01:47,466 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 576062ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-21 00:11:43,550 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 576062ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-21 00:15:39,659 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 196101ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

2020-03-21 00:51:03,009 ERROR 95488 nodejs.ClusterClientNoResponseError: client no response in 2103330ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/yao37/projects/practices/graduation-project/egg_system/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 95488
hostname: zhendeMacBook-Pro.local

